- hosts: tag_ansible_dc01
  name: Configure Active Directory on DC01
  vars:
    ansible_user: "{{ azurevmuser }}"
    ansible_password: "{{ azurevmpw }}"
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_message_encryption: always
  tasks:
    - name: Configure AD
      include_role:
        name: jesperberth.active_directory_domain
      vars:
        domain: "testdomain.local"
        safemodepw: "SomePassword"